### ISSUE TITLE
About applicability of cadet in quantifier elimination 

### ISSUE THREAD

**Issue by dong-yf** [MarkusRabe/cadet#13]
I'm wondering if cadet can be applied to quantifier elimination for only exist-quantifer formulas, like ∃ y. $\phi $. If yes, which    parameter should be used to generate quantifier elimination results.
I have this problem because when I apply `cadet -e` to formulas(in QDIMACS) which only contain exist quantifier, it comes to generate aag file like this, which seems not to be right. So I'm wondering if I use cadet in the wrong way or cadet just can't do it, thanks.
```
aag 0 0 0 1 0
1
o0 There is an assignment to the existentials
```

**Comment by MarkusRabe** [comment]
Hey! I am not sure if I fully understand your question. As far as I know there is just one kind of quantifier elimination, and the confusion may be because you have free variables, while in the format that these tools are working these variables have to be universally quantified. In short, the variables that you intend to keep need to be universally quantified, and the variables that you want to eliminate need to be existentially quantified (forall X. exists Y: phi).
