### ISSUE TITLE
could not understand this error. ?

### ISSUE THREAD

**Issue by HarishUth** [MarkusRabe/cadet#9]
![Screenshot from 2019-05-08 11-47-02](https://user-images.githubusercontent.com/45685124/57353701-f6b31a80-7186-11e9-8ee2-08a07bb207bd.png)

![Screenshot from 2019-05-08 11-47-54](https://user-images.githubusercontent.com/45685124/57353738-18ac9d00-7187-11e9-87f5-1866ec151489.png)

This is the error i am getting during the execution of the qdimacs file. 
Can you please tell me what the problem is?

**Comment by MarkusRabe** [comment]
This is an  odd bug. Thanks for bringing this to my attention!

After some experimentation, it appears that the bug is due to trailing whitespaces in your file. For some reason the parser chokes on this. Let me know if removing trailing whitespaces helps.

I'll also prepare a bugfix later this week.

**Comment by HarishUth** [comment]
Yes sir. It did help! I typed the example program and the compiler compiled
it without errors.
Thank you so much for helping.
